### ISSUE TITLE
Be smarter about starting JavaFX apps

### ISSUE THREAD

**Issue by mikehearn** [mikehearn/graviton-browser#16]
We can always invoke a sub-JVM of course, but for now let's continue to flesh out support for running apps in the same JVM as the shell window. This may have advantages later if we want to provide extra functionality or tabbed UIs.

For now, when we locate the main class, if it's a JavaFX application let's not invoke the main method directly but rather directly invoke the Application class - as the Java launcher can do.

For bonus points we can examine the main method to see if all it does is call `Application.launch` - but for now there's not much we can do if it does more than that, beyond run a sub-JVM.

**Comment by mikehearn** [comment]
Done in 28494e8c499dc547ba085c21d85e5ec50036daf1

**Comment by fthevenet** [comment]
Is there a way for a JavaFX app to opt-out of this behaviour and run in its own JVM? The reason is that if an an app relies on ServiceLoaders to instantiate parts of its components, those never get a chance to be loaded if the app if bootstrapped from an already existing JVM.
This is the same problem that arises when trying to start an app off a Maven repo using the exec:java goal in the Maven Exec plugin (in which case you can work around the issue by using the exec:exec goal, which spawns a new JVM).

**Comment by mikehearn** [comment]
@fthevenet Yes, by default apps are now run in a separate JVM unless you opt in to reusing the Graviton JVM.

I don't fully understand the ServiceLoader issue though. Can you elaborate? Why wouldn't it work?

**Comment by mikehearn** [comment]
Are you referring to the JDBC driver issue, where any reference to Driver triggers a one-time load of drivers?

**Comment by fthevenet** [comment]
My comment about ServiceLoader stem from my observation of how my own application, which uses them to load plugins, behaved when I tried to use the [exec-maven-plugin](https://www.mojohaus.org/exec-maven-plugin/) to achieve something similar to what Graviton does (e.g. run an app from its maven GAV coordinates).
Namely, when using the goal exec:java, which launches the target JAR on the same JVM as maven, plugins would fail to load, while when using the goal exec:exec which would spawn a new and independent JVM, everything worked fine.  
My understanding of the issue is that it originates from the fact the exec-maven-plugin creates a dedicated class loader for the app it starts while the provider-configuration files are still being located by the bootstrap class loader: the result being than when my app tries to load services, no providers are visible to it.

With all that said, I probably was a bit quick to jump to conclusion as, while the issue looks similar from the outside, something quite different my be going on it this case.  
I will investigate this further and open a new issue if it appears there is no way to fix it on my end.

**Comment by mikehearn** [comment]
Ah. Well that sounds like a bug in the Maven plugin - classloaders are used to locate resources too, so if their classloader wasn't looking in the right places for them I guess, it was a bug on their end.

I know of one issue related to JDBC specifically, because Graviton accidentally initialises JDBC during startup via the PicoCLI command line parsing framework, and JDBC driver loading is cached. So you get one shot. It's not very good, I'd consider it a JDK bug actually, but unfortunately true in-JVM isolation in Java doesn't work so brilliantly, it will need some cooperation from the app unless the JVM improves. But there's a lot we can do still with the existing functionality to improve it.
