### ISSUE TITLE
TornadoFX charts sample demo has stopped working

### ISSUE THREAD

**Issue by mikehearn** [mikehearn/graviton-browser#39]
1. I can't download it anymore. Jitpack issue?
2. Tommy who could download it, can't start it. Looks like an issue finding the main class.

```2018-10-12 09:01:14 INFO [main] AppLauncher.searchForAndInvokeJFXAppClass()
No main class, searching for a JavaFX Application subclass
2018-10-12 09:01:14 INFO [main] GravitonClassLoader.invoke()
Searching for a JavaFX Application class completed immediately.```

**Comment by tlil** [comment]
Just to clarify, it first got stuck when downloading from the GUI. I tried to cancel it, but that didn't work, so I quit Graviton. Next time I opened the GUI, the app showed up in the cache. But this time it got stuck when trying to initialise the app.

**Comment by tlil** [comment]
So my second issue could just be that it _thinks_ it has the JARs in its local cache, when it only has a partial download or something....?

**Comment by tlil** [comment]
Yep, updated above

**Comment by mikehearn** [comment]
Well, the charts-master JAR is of the right size at least. I was able to reproduce your situation perfectly, including the failure to load after a restart of the app. How strange.

I was changing the startup code last week so I'm not surprised there are odd regressions in this area. I was testing with different apps and they all worked. One of the tasks on the todo list is to select an initial group of apps that exercise the various codepaths and add automated GUI tests for them using e.g. TestFX

Will investigate over the weekend.

**Comment by belu** [comment]
Also investigated this issue a little bit. For me the download is working, however no JavaFX application class is found and the GUI is hanging in state "Please wait. App is initializing".

As a first improvement how about the following change in `GravitonClassLoader.foundJFXClass()`:
Instead of returning `null `at the end of the stopwatch code throw a `AppLauncher.StartException` with appropriate message (e. g. "Failed to find JavaFX Application class"). This would show a correct error message to the user and the app is going to a state where the user does not expect an app to be started.

Second thing I noticed:
Also in `GravitonClassLoader.foundJFXClass()` just the first URL is used to scan for a JavaFX `Application `class. In the given case of the TornadoFX samples however this URL just points to a ZIP with only a Manifest file in it (`tornadosfx-samples-master.jar`). Therefore no chance to find an `Application `class.

Maybe one has to iterate over all URLs until one with an `Application` class is found? This of course leads to new questions: What if there are several `Application `classes found? In this case use the first one?

**Comment by belu** [comment]
@mikehearn @tlil 

Finally was able to get the ChartApp started:
Interestingly in `GravitonClassLoader.foundJFXClass` when searching for `javafx.application.Application` that does not find the ChartApp. However, when searching for `tornadofx.App` it is able to locate it.

However, this whole approach still feels a little bit hacky. Furthermore, when closing the ChartsApp I get a RuntimeException: "A bound value cannot be set." (that is the title is set manually but already bound somewhere).

**Comment by belu** [comment]
@mikehearn @tlil 
Regarding the RuntimeException: an `unbind()` of the `titleProperty()` in the `restore()` method in `AppLauncher` before setting the title back to "Graviton" solves that problem.

**Comment by mikehearn** [comment]
Fixed by Bernhard
